name: CI workflow

#When to run the workflow
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
#Jobs to run
jobs:
  #Build job to run on ubuntu-latest runner with python 3.9 container
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
  #Steps to run in the build job
  steps:
    #Checkout the repository
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: | #| is used to run multiline commands
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Lint with flakes8
      run: |
        flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

    - name: Run unit tests with nose
      run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app